DATA:
  data_root: /data/camvid
  train_list: /data/camvid/list/train.txt
  val_list: /data/camvid/list/val.txt
  classes: 11


TRAIN:
  arch: segnet
  sync_bn: true  # adopt syncbn or not
  train_h: 360
  train_w: 480
  zoom_factor: 8  # Just to prevent rescaling, not nice
  scale_min: 0.25  # minimum random scale
  scale_max: 1.0  # maximum random scale
  rotate_min: -10  # minimum random rotate
  rotate_max: 10  # maximum random rotate
  ignore_label: 11
  aux_weight: 0
  train_gpu: [0]
  workers: 4  # data loader workers
  batch_size: 8  # batch size for training
  batch_size_val: 8  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.01
  epochs: 450
  start_epoch: 0
  power: 0.9
  momentum: 0.9
  lr_schedule: cosine
  weight_decay: 0.0005
  manual_seed: 2
  print_freq: 50
  save_freq: 20
  save_path: /logs/exp/camvid/segnet_0.9375_300_seed2_annealed/model
  weight:  # path to initial weight (default: none)
  resume:  # path to latest checkpoint (default: none)
  evaluate: false  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
  sparsity: 0.9375
  starting_epoch: 0
  ending_epoch: 300
  learnable_weights: false
Distributed:
  dist_url: tcp://127.0.0.1:5002
  dist_backend: nccl
  multiprocessing_distributed: true
  world_size: 1
  rank: 0

TEST:
  test_list: /data/camvid/list/test.txt
  split: val # split in [train, val and test]
  base_size: 480 # based size for scaling
  test_h: 360
  test_w: 480
  scales: [1.0]    # evaluation scales, ms as [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
  has_prediction: false # has prediction already or not
  index_start: 0  # evaluation start index in list
  index_step: 0  # evaluation step index in list, 0 means to end
  test_gpu: [0]
  model_path: /logs/exp/camvid/segnet_0.9375_300_seed2_annealed/model/train_epoch_450.pth  # evaluation model path
  save_folder: /logs/exp/camvid/segnet_0.9375_300_seed2_annealed/result/epoch/val/ss  # results save folder
  colors_path: data/camvid/camvid_colors.txt  # path of dataset colors
  names_path: data/camvid/camvid_names.txt  # path of dataset category names
  calc_results: true
  result_path: /logs/exp/evals/camvid_segnet_0.9375_300_seed2_annealed.csv # evaluation result path
  sparse: true
